version: '3'
services:
  test:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache-volume:/cache
    links:
      - db
    depends_on:
      - db
      - agent
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravelbackend
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - default
  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache-volume:/cache
    entrypoint: "build.sh"
  agent:
    image: michaelmnm/ansible:latest
    links:
      - db
    depends_on:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]
  db:
    image: mysql:latest
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: laravelbackend
      MYSQL_ROOT_PASSWORD: password
volumes:
  cache-volume:
    external: true